# Generated by Django 4.1.7 on 2023-05-06 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='user_email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
