# Generated by Django 4.1.7 on 2023-05-06 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_portfolio_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='stock_symbol',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
