# Generated by Django 4.1.7 on 2023-05-06 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_portfolioitem_stock_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='transaction_type',
            field=models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], default='buy', max_length=4),
        ),
    ]
