# Generated by Django 4.1.7 on 2023-05-06 18:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_portfolioitem_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='transaction_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
