# Generated by Django 4.1.7 on 2023-06-02 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_portfolioitem_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True),
        ),
    ]
