# Generated by Django 4.1.7 on 2023-03-30 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
