# Generated by Django 4.1.7 on 2023-03-07 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summarized_news', '0002_rename_summarizednews_summarizedarticle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SummarizedArticle',
        ),
    ]
