# Generated by Django 4.1.7 on 2023-06-03 01:12

from django.db import migrations, models


from django.db import migrations, models

def generate_unique_usernames(apps, schema_editor):
    User = apps.get_model('users', 'User')

    for user in User.objects.all():
        if user.name:
            user.username = f"{user.name.replace(' ', '_')}_{user.id}"
        else:
            user.username = f"user_{user.id}"
        user.save()

class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(generate_unique_usernames),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255, unique=True, null=False),
        ),
    ]


