# Generated by Django 4.1.7 on 2023-04-26 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_portfolio', '0002_alter_portfolio_user'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='portfolio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_portfolio', to='stock_portfolio.portfolio'),
        ),
    ]
